### ISSUE TITLE
How to handle duplicate packages ?

### ISSUE THREAD

**Issue by mbugeia** [YunoHost/apps#3]
For Seafile the community list point to https://github.com/CotzaDev/seafile_ynh, I (with great contributors) also maintain a package of seafile on https://github.com/mbugeia/seafile_ynh wich IMHO is in a better state (webdav config, logrotate script, better upgrade script).

In fact the other package have cause issue in the past by a broken remove script (see https://forum.yunohost.org/t/seafile-package/439/11)

How do you suggest to handle this ?

**Comment by Kloadut** [comment]
Good question.

For now the CotzaDev package being in a dirty state, you can Pull Request by replacing your package in the list.

For the future though, it will require from packagers to change the app id (`seafile` -> `seafile_something`). But this should not be too frequent now that we have a centralized list of community contributions. Debates in pull requests will be ok I guess. :-)

**Comment by mbugeia** [comment]
Ok, I will do a PR to update the Seafile repository. I agree that it should not be too frequent and changing the app id could be a good workaround.

**Comment by M5oul** [comment]
[YunoHost-Apps organization](https://github.com/YunoHost-Apps) help solve that issue.
